config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :accounts, only: [:index, :show, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show, :edit, :update]
  end

  devise_for :admins, controllers: {
    :passwords => 'admins/passwords',
    :sessions => 'admins/sessions'

  }
  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'about' => 'homes#about'
  get 'search/search'


  resources :recipes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resource :reviews, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :makings, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'account/quit' => 'accounts#quit'
  patch 'account/out' => 'accounts#out'
  put 'account/out' => 'accounts#out'

  resources :accounts, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    resources :crops, only: [:index, :new, :create, :edit, :update, :destroy]
    get '/account_index' => 'recipes#account_index'
  end
  
  resources :contacts, only: [:index, :show, :new, :create, :destroy]

  resources :categories, only: [:new, :create, :destroy, :index, :edit, :update] do
    get '/category_index' => 'recipes#category_index'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  attachment :image
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  #-------------バリデーション-----------------
  with_options presence: true do
    validates :title
    validates :category
    validates :text
  end
  #--------------------------------------------


  enum category:{
    "その他": 0,
    "生産者申請": 1,
    "不具合・修正依頼": 2
  }

  enum status:{
    "未処理": 0,
    "承認済み": 1,
    "否認": 2
  }

end

app/models/crop.rb
class Crop < ApplicationRecord
  attachment :image

  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :recipe
end

app/models/making.rb
class Making < ApplicationRecord
  attachment :image
  belongs_to :recipe
  
  #--------------------------------------------
  validates :process, presence: true
  #--------------------------------------------
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attachment :image

  acts_as_taggable   # acts_as_taggable_on :tags の省略
  acts_as_taggable_on :skills, :interests  # @recipe.skill_list とかが使えるようになる


  belongs_to :user
  has_many :making, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recipe_ai_tags, dependent: :destroy


  #-------------バリデーション-----------------
  with_options presence: true do
    validates :name
    validates :ingredients
    validates :image
  end
  #--------------------------------------------

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/recipe_ai_tag.rb
class RecipeAiTag < ApplicationRecord
  belongs_to :recipe
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
  validates :comment, presence: true
  
  belongs_to :user
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
   attachment :image

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :reviews
  has_many :favorites
  has_many :contacts, dependent: :destroy
  has_many :crops, dependent: :destroy


  #----------フォロー機能中間テーブル----------
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy

  has_many :followers, through: :reverse_of_relationships, source: :follow
  has_many :follows, through: :relationships, source: :followed
  #--------------------------------------------

  #---------バリデーション------------------
  with_options presence: true do
    validates :first_name
    validates :last_name
    validates :first_name_kana
    validates :last_name_kana
    validates :nickname
  end
  #-----------------------------------------



  def your_farmer
    if self.is_farmer == true
      self.nickname + "(公認ユーザー）"
    else
      self.nickname
    end
  end

  def full_name
      self.last_name + self.first_name
  end

  # フォロー機能定義
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    follows.include?(user)
  end
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  def index
    @crops = Crop.where(user_id: params[:account_id])
  end

  def new
    @crop = Crop.new
  end

  def create
    @crop = Crop.new(crop_params)
    @crop.save
    redirect_to account_crops_path(current_user.id)
  end

  def edit
    @crop = Crop.find(params[:id])
  end

  def update
    @crop = Crop.find(params[:id])
    @crop.update(crop_params)
    redirect_to account_crops_path(current_user.id)
  end

  def destroy
    @crop = Crop.find(params[:id])
    @crop.destroy
    redirect_to account_crops_path(current_user.id)
  end


  private

  def crop_params
    params.require(:crop).permit(:user_id, :image, :introduction)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/makings_helper.rb
module MakingsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/crops/edit.html.erb
<div class="container">
  <h1>Crops#edit</h1>
  <div class="row">
    <%= form_with model: @crop, url: account_crop_path(@crop.user_id, @crop.id), local:true do |f| %>
      <div class="col-12 my-3">
        <%= f.label :"投稿画像" %><br>
        <%= f.attachment_field :image %>
      </div>
      <div class="col-12 my-3">
        <%= f.label :"投稿画像紹介" %><br>
        <%= f.text_area :introduction, class: "crop_introduction_box" %>
      </div>
      <div class="col-12 my-3">
        <%= f.submit '更新する', class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/crops/index.html.erb
<div class="container">
  <h1>Crops#index</h1>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>投稿画像</th>
        <th>投稿画像紹介文</th>
        <th>
          <%= link_to new_account_crop_path(current_user.id) do %>
            <button type="button" class="btn btn-success">新規登録する</button>
          <% end %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @crops.each do |crop| %>
        <tr>
          <td>
            <div class="category_image">
              <%= attachment_image_tag(crop, :image, fallback: "no_image.jpg") %>
            </div>
          </td>
          <td><%= simple_format(crop.introduction) %></td>
          <td>
            <span class="making_edit">
              <%=link_to '編集する', edit_account_crop_path(crop.user_id, crop.id)  %>
            </span>
            <br><br>
            <span class="making_destroy">
              <%=link_to '削除する', account_crop_path(crop.user_id, crop.id), method: :delete  %>
            </span>
          </td>
        </tr>
      <% end %>
  </div>
</div>

app/views/crops/new.html.erb
<div class="container">
  <h1>Crops#new</h1>
  <div class="row">
    <%= form_with model: @crop, url: account_crops_path(current_user.id), local:true do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="col-12 my-3">
        <%= f.label :"投稿画像" %><br>
        <%= f.attachment_field :image %>
      </div>
      <div class="col-12 my-3">
        <%= f.label :"投稿画像紹介文" %><br>
        <%= f.text_area :introduction, class: "crop_introduction_box" %>
      </div>
      <div class="col-12 my-3">
        <%= f.submit '新規登録する', class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>