config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :accounts, only: [:index, :show, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show, :edit, :update]
  end

  devise_for :admins, controllers: {
    :passwords => 'admins/passwords',
    :sessions => 'admins/sessions'

  }
  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'about' => 'homes#about'
  get 'search/search'


  resources :recipes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resource :reviews, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :makings, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'account/quit' => 'accounts#quit'
  patch 'account/out' => 'accounts#out'
  put 'account/out' => 'accounts#out'

  resources :accounts, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    resources :crops, only: [:index, :new, :create, :edit, :update, :destroy]
    get '/account_index' => 'recipes#account_index'
  end
  
  resources :contacts, only: [:index, :show, :new, :create, :destroy]

  resources :categories, only: [:new, :create, :destroy, :index, :edit, :update] do
    get '/category_index' => 'recipes#category_index'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  attachment :image
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  #-------------バリデーション-----------------
  with_options presence: true do
    validates :title
    validates :category
    validates :text
  end
  #--------------------------------------------


  enum category:{
    "その他": 0,
    "生産者申請": 1,
    "不具合・修正依頼": 2
  }

  enum status:{
    "未処理": 0,
    "承認済み": 1,
    "否認": 2
  }

end

app/models/crop.rb
class Crop < ApplicationRecord
  attachment :image

  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :recipe
end

app/models/making.rb
class Making < ApplicationRecord
  attachment :image
  belongs_to :recipe
  
  #--------------------------------------------
  validates :process, presence: true
  #--------------------------------------------
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attachment :image

  acts_as_taggable   # acts_as_taggable_on :tags の省略
  acts_as_taggable_on :skills, :interests  # @recipe.skill_list とかが使えるようになる


  belongs_to :user
  has_many :making, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recipe_ai_tags, dependent: :destroy


  #-------------バリデーション-----------------
  with_options presence: true do
    validates :name
    validates :ingredients
    validates :image
  end
  #--------------------------------------------

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/recipe_ai_tag.rb
class RecipeAiTag < ApplicationRecord
  belongs_to :recipe
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
  validates :comment, presence: true
  
  belongs_to :user
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
   attachment :image

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :reviews
  has_many :favorites
  has_many :contacts, dependent: :destroy
  has_many :crops, dependent: :destroy


  #----------フォロー機能中間テーブル----------
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy

  has_many :followers, through: :reverse_of_relationships, source: :follow
  has_many :follows, through: :relationships, source: :followed
  #--------------------------------------------

  #---------バリデーション------------------
  with_options presence: true do
    validates :first_name
    validates :last_name
    validates :first_name_kana
    validates :last_name_kana
    validates :nickname
  end
  #-----------------------------------------



  def your_farmer
    if self.is_farmer == true
      self.nickname + "(公認ユーザー）"
    else
      self.nickname
    end
  end

  def full_name
      self.last_name + self.first_name
  end

  # フォロー機能定義
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    follows.include?(user)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @users = User.where(is_farmer: "true")
  end

  def show
    @user = User.find(params[:id])
    @myrecipes = Recipe.where(user_id: @user.id)
    @pick_up = Recipe.where(user_id: @user.id, recommend: true)
    @crops = Crop.where(user_id: @user.id)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(account_params)
    redirect_to account_path(current_user)
  end

  def quit
    @user = current_user
  end

  def out
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def account_params
    params.require(:user).permit(:first_name, :first_name_kana, :last_name, :last_name_kana, :introduction, :email, :nickname, :image)
  end
end

app/controllers/admins/accounts_controller.rb
class Admins::AccountsController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(account_params)
    redirect_to admins_account_path(@user)
  end

  def destroy
  end


  private

  def account_params
    params.require(:user).permit(:first_name, :first_name_kana, :last_name, :last_name_kana, :email, :nickname, :is_farmer, :is_deleted)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admins/accounts_helper.rb
module Admins::AccountsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/makings_helper.rb
module MakingsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/accounts/edit.html.erb
<div class="container">
  <h1>～アカウント編集～</h1>
    <%= form_with model: @user, url:account_path, local:true do |f| %>
    <div class="row">
      <div class="col-12 my-2">
        <%= f.label :"アイコン画像" %><br>
        <%= f.attachment_field :image %><br>
      </div>

      <div class="col-12 my-2">
        <%= f.label :"ニックネーム" %><br>
        <%= f.text_field :nickname %>
      </div>

      <div class="col-4 my-2">
        <%= f.label :"姓" %><br>
        <%= f.text_field :last_name %>
      </div>

      <div class="col-6 my-2">
        <%= f.label :"名" %><br>
        <%= f.text_field :first_name %>
      </div>

      <div class="col-4 my-2">
        <%= f.label :"姓（ふりがな）" %><br>
        <%= f.text_field :last_name_kana %>
      </div>

      <div class="col-6 my-2">
        <%= f.label :"名（ふりがな）" %><br>
        <%= f.text_field :first_name_kana %>
      </div>

      <div class="col-12 my-2">
        <%= f.label :"紹介" %><br>
        <%= f.text_area :introduction, class: "account_intoroduction_form" %>
      </div>

      <div class="col-12 my-2">
        <%= f.submit "アカウント情報を変更", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/accounts/index.html.erb
<div class="container">
  <h1>生産者アカウント</h1>
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-3">
        <p>
          <%= attachment_image_tag(user, :image, size: "200x200", fallback: "no_image.jpg") %>
        </p>
        <%= link_to account_path(user.id) do %>
          <%= user.nickname %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/accounts/quit.html.erb
<div class="quit">
  <p class="text-center">本当に退会しますか？</p>
  <p class="text-center">
    退会すると、このアカウントの会員情報の閲覧や<br>
    レシピの投稿ができなくなります。<br>
    退会する場合は、「退会する」をクリックしてください。<br>
  </p>

  <div class="text-center">
    <%= link_to '退会しない', account_path(@user), class: "btn btn-primary" %>
    <%= link_to '退会する', account_out_path, method: :patch, class: "btn btn-danger" %>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="container">
  <h1>～<%= @user.your_farmer %>のマイページ～</h1>
  <div class="row">
    <div class="col-xs-col-12 col-lg-8">
      <div class="account_name_area">
        <div class="account_icon">
          <%= attachment_image_tag(@user, :image, size: "200x200", fallback: "no_image.jpg") %>
        </div>
        <div class="account_name">
          <br>
          <p><span class="border-orange">ニックネーム</span><br><b><%= @user.nickname %></b></p>
　        <p>フォロー数：<%= @user.follows.count %><br>フォロワー数：<%= @user.followers.count %></p>
　        <% if user_signed_in? %>
　          <% if @user == current_user %>
　          <% else %>
    　         <% if current_user.following?(@user) %>
                <%= link_to "フォロー外す", account_relationships_path(@user.id), method: :delete, class: "btn btn-primary" %>
              <% else %>
                <%= link_to "フォローする", account_relationships_path(@user.id), method: :post, class: "btn btn-success" %>
              <% end %>
            <% end %>
          <% else %>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <% if @user == current_user %>
            <div class="account_option">
              <h5 class="account_option_head">アカウントオプション</h5>
              <div class="new_recipe_button">
                <%= link_to new_recipe_path do %>
                  <p>レシピ新規登録</p>
                <% end %>
              </div>
              <div class="contact_button">
                <p><%= link_to 'お問い合わせ', contacts_path %></p>
              </div>
              <div class="edit_button">
                <%= link_to edit_account_path(@user.id) do %>
                  <p>編集する</p>
                <% end %>
                <%= link_to account_quit_path do %>
                  <p>退会する</p>
                <% end %>
              </div>
              <% if @user.is_farmer == true %>
                <h5 class="account_option_head">生産者オプション</h5>
                  <div class="farmer_option">
                    <%= link_to account_crops_path(@user.id) do %>
                      <p>生産物紹介編集</p>
                    <% end %>
                  </div>
              <% end %>
            </div>
          <% else %>
          <% end %>
        <% else %>
        <% end %>

      </div>
      <div class="account_intoroduction">
        <%= simple_format(@user.introduction) %>
      </div>
      <div class="pick_up">
  <!-- 一般ユーザーだった場合にはおすすめのレシピ表示 -->
        <% if @user.is_farmer == false %>
        <h4>~おすすめレシピ！~</h4>
        <div class="slide">
          <% @pick_up.each do |pick_up| %>
            <div class="pick_up_image">
              <%= attachment_image_tag(pick_up, :image) %>
              <p class="text_center"><b><%= pick_up.name %></b></p>
            </div>
          <% end %>
        </div>
  <!-- 生産者ユーザーだった場合には生産物表示 -->
        <% else %>
          <% if @crops.count == 0 %>
          <% else %>
            <h4>~私が作りました！~</h4>
            <div class="slide">
              <% @crops.each do |crop| %>
                <div class="pick_up_image">
                  <%= attachment_image_tag(crop, :image) %>
                  <div class="pick_up_crop">
                    <%= crop.introduction %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-lg-4">
      <div class="posting_recipe">
        <p>投稿したレシピ  <%= @myrecipes.count %>件</p>
      </div>
      <div class="my_posting_recipe">
        <% @myrecipes.last(4).each do |myrecipe| %>
          <%= link_to recipe_path(myrecipe.id) do %>
            <%= attachment_image_tag(myrecipe, :image, size: "270x180", fallback: "no_image.jpg") %>
          <% end %>
          <p><%= myrecipe.name %></p>
        <% end %>
      </div>
      <%= link_to account_account_index_path(@user.id) do %>
        <p><%= @user.nickname %>さんのすべてのレシピ</p>
      <% end %>
    </div>
  </div>
</div>